### ISSUE TITLE
[@fab/deployer-aws-lambda] Origin update?

### ISSUE THREAD

**Issue by thejuan** [fab-spec/fab#181]
I followed the guide for deploying to Lambda@Edge
The default CF template has linc specific domains for the origins.
I had assumed the fab deploy would update these to match the deploy settings, but it doesn't seem to.

The static origin should be the s3 bucket?
What's the origin for the renderer?

**Comment by evanderkoogh** [comment]
Hey @thejuan, you have stumbled on an interesting conundrum. Because the Lambda@Edge will create the responses to all requests, there are no request that will ever go to the origin. So we don't need it, but CloudFront needs to have an origin set.

So we have settled for the using a static domain that basically says "If you can see this page, something is wrong in your FAB config".. We would have used a fab.dev domain, but then we get into trouble if it is called from another Cloudflare Workers sometimes.

But we can probably add a bit of explanation to the CF template why there is a Linc specific thing in there.

Did you get your FAB running on Lambda@Edge?

**Comment by thejuan** [comment]
Ahh! I should have just tried it :)
It is indeed working.

I had to remove the lambda association from the CF template as was getting a permissions error.
The fab deploy associated it fine for me.

Then had to monkey patch the aws cred stuff from #180

**Comment by evanderkoogh** [comment]
Which is a good point actually. We can just remove the entire CF template and just call the API endpoints directly in the deployer.

**Comment by thejuan** [comment]
It is nice to have some finer grain control over the CF, like cnames. But if that was still exposed somehow in the advanced scenario, it would make setup much quicker

**Comment by evanderkoogh** [comment]
Yeah, we can absolutely surface that in some way or another.
