### ISSUE TITLE
Dynamic pages in NextJS return a 404

### ISSUE THREAD

**Issue by evanderkoogh** [fab-spec/fab#45]
Buildkite is having an issue with dynamic pages. Those pages work in a local next dev environment, but not when wrapped in fab.

The commit with the first dynamic page is: https://github.com/buildkite/site/pull/573/commits/91385a480eac63699a89f2209bb33dc7cdecc58b

The PR for it is: https://github.com/buildkite/site/pull/573

And as you can see on https://buildkite-site--production--lh-plugin-pages.branch.linc-preview.sh/plugins/buildkite-plugins-docker-compose-buildkite-plugin this return a 404.

**Comment by geelen** [comment]
Ahhhhh, got it.

So with NextJS 9, they introduced this idea that if a page doesn't have anything server-side on it (i.e. no `getInitialProps`), then it would collapse at build-time to a static HTML file. I added code to handle that, and I _also_ added code to handle dynamic pages like `/plugins/[plugin].js`. But I'd never thought how they might interplay.

I honestly don't know _how_ Next is handling it, maybe it's find-replacing on the string at runtime? Maybe there's something in there to handle this exact case. Will investigate.

Can be fixed by adding `getInitialProps` to that page. See https://github.com/geelen/buildkite-site/pull/1/files for the diff and https://geelen-buildkite-site--c1c4ccd33--production.linc-preview.sh/plugins/buildkite-plugins-docker-compose-buildkite-plugin to see that it's now working.

**Comment by lachlanhardy** [comment]
Cheers, Glen, worked a treat! https://github.com/buildkite/site/pull/573/commits/f42d965f164a346466e6f6bf281b72c1f52d677f
